Quotes, asyncpraw + cleaning some code
TesseractCoding/Ric-Bot pull request #14
Opened 2021-04-17 04:37 UTC by ricardoprins

This solves #10 and #11, plus cleans up code a little bit.

2021-04-17 04:45 UTC, ricardoprins commented
I need to delete one unnecessary line - will fix the PR after I wake up (it's the random print statement at the end of the quotes module)

2021-04-17 09:27 UTC, gat786 requested changes

2021-04-17 09:27 UTC, gat786 commented on Pipfile
> +asyncpraw = "*"
It's better if we use perfect version numbers for our libraries

2021-04-17 09:27 UTC, gat786 commented on src/modules/quotes.py
> +print(getQuote())
This line prints a quote as log when we start the app. Also look at the line endings

2021-04-17 09:27 UTC, gat786 commented on src/modules/client.py
>              await message.channel.send("pong")
I guess we can improve this if-else ladder by using a switch case.

2021-04-17 09:29 UTC, gat786 commented
Also try to keep the structure level changes to a minimal this is the second time we are making structure level changes. If you are confused we can decide a way for making everything accurate. But disturbing the main code again and again is something that i would like to keep at minimum.

2021-04-17 20:28 UTC, ricardoprins commented on src/modules/quotes.py
> +print(getQuote())
"I need to delete one unnecessary line - will fix the PR after I wake up (it's the random print statement at the end of the quotes module)" (first comment above)

2021-04-17 20:30 UTC, ricardoprins commented on src/modules/client.py
>              await message.channel.send("pong")
I'd be glad to do it in C if I could...

I'll refactor this whole chain later to the commands.py so that all commands are only changed there.

2021-04-17 20:31 UTC, ricardoprins commented
> Also try to keep the structure level changes to a minimal this is the second time we are making structure level changes. If you are confused we can decide a way for making everything accurate. But disturbing the main code again and again is something that i would like to keep at minimum.

What do you mean by "structure level changes"?

2021-04-18 16:40 UTC, gat786 reviewed
LGTM

2021-04-18 17:26 UTC, merged