Added help function and decode in memes.py
TesseractCoding/Ric-Bot pull request #20
Opened 2021-04-18 13:07 UTC by adnan007d

2021-04-18 16:06 UTC, ricardoprins commented
Hi!

Great job. We've had another PR changing the client.py. Could you handle these conflicts? 
Also, could you squash/rebase your PR so that you have a single commit?

2021-04-18 17:42 UTC, adnan007d commented
Should I push the resolved conflict directly to the master branch or create a new branch ?

2021-04-19 04:46 UTC, gat786 commented
When you have conflicts what you do is pull the branch with which you are having a conflict and try to merge it with the local branch at your machine. You fix those issues on your machine. After they are fixed you push the code. No need to create another branch. [This](https://www.youtube.com/watch?v=Mfz8NQncwiQ&t=982s&ab_channel=ScottHanselman) video might help you understand it.

2021-04-19 16:03 UTC, ricardoprins requested changes
After you fix the help file, it would be great if you could squash/rebase all your commits into a single one.

2021-04-19 16:03 UTC, ricardoprins commented on src/modules/help.py
> +<<<<<<< HEAD
These lines should be removed (the ones added during the merge process by git)

2021-04-19 16:04 UTC, ricardoprins requested changes

2021-04-19 16:04 UTC, ricardoprins commented on src/modules/help.py
> +=======
lines 7, 9, and 11

2021-04-19 18:10 UTC, adnan007d commented
Did the squash worked ? I had multiple conflicts while doing it

2021-04-19 19:57 UTC, ricardoprins commented
It didn't - when it works, you'll only see one commit in your PR. Let me share some links that might help you :)

https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request
https://blog.carbonfive.com/always-squash-and-rebase-your-git-commits/

2021-04-20 06:24 UTC, adnan007d commented
:smiley: Finally done!! It took me a while to figure it out and the article helped a lot

2021-04-20 06:27 UTC, gat786 commented
Lets goo!

2021-04-20 06:27 UTC, gat786 commented
For PR's I need to write some different github action this action fails everytime.

2021-04-20 06:30 UTC, gat786 commented
What I would suggest you Adnan is don't stage files to commit which you don't intend to commit. Right now, there are like 6 files changes out of which you worked on only 2-3 of them. Now benefit of staging only files you need to change is that you don't change much of the codebase until you need to.

2021-04-20 06:35 UTC, adnan007d commented
Okay, then no need to staged  files like pipfile, piplock and all then config files which I didn't change manually

2021-04-20 08:00 UTC, gat786 commented
Yep remove them from the commits.

2021-04-20 14:04 UTC, adnan007d commented
Is it failing because of this command ? 
python -m pipenv run pylint `ls -R|grep .py$|xargs`
in pylint.yml
python -m pipenv run pylint `find . | grep .py$|xargs` 
I think this one should work fine

2021-04-20 18:59 UTC, gat786 commented
I can still see the changes to workflow files in your commits and theres also a change to pipfile.lock.

2021-04-20 19:17 UTC, ricardoprins commented
> I can still see the changes to workflow files in your commits and theres also a change to pipfile.lock.

I thought those were meant to be there, my bad!

2021-04-21 05:35 UTC, adnan007d commented
:rocket: :tada:  Finally done!! :smiley:

2021-04-21 07:58 UTC, gat786 commented
Now your PR looks so clean. 👍🏼 These small tricks can help maintainers so much when applied in a good way.

2021-04-21 08:22 UTC, gat786 commented
Locally this build works. And Im accepting this PR. Thanks for contributing.

2021-04-21 08:23 UTC, merged

2021-04-21 08:23 UTC, gat786 commented
You are the first contributor outside of Tesseract Coding to contribute to Ric-Bot. Thanks for taking time and doing this.

2021-04-21 16:44 UTC, ricardoprins commented
Amazing, thanks @adnan007d!